sudo: false

language: go
go:
  - 1.8.x

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get -u github.com/FiloSottile/gvt

script:
  - gvt restore
  - make ci
  - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN

notifications:
  email: false