sudo: false

language: go
go:
  - 1.8.x

before_install:
  - go get -u github.com/FiloSottile/gvt
  - go get github.com/tj/mmake
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - gvt restore
  - mmake vet
  - mmake test
  - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN

notifications:
  email: false